homeserver:
  # The url is the url used to talk to your server.
  url: 'http://localhost:8008'

  # The server_name is the part that shows up in @username:server_name. This
  # is usually the domain of the url, but may be different if you use an SRV
  # record or a .well-known URI
  server_name: 'localhost'
  server_type: 'synapse'

appservice:
  # The port the homeserver uses to talk to the appservice (connector). This can
  # be an arbitrary unused port.
  port: 9995

  # The hostname the homeserver uses to talk to the appservice. This hostname
  # should be accessible from the homeserver. If they are on the same server,
  # set it to localhost.
  hostname: host.docker.internal

  # The host the appservice server should bind to. Defaults to hostname
  bind: 0.0.0.0

  schema: http

# URL to the mattermost instance.
mattermost_url: http://localhost:8065/

# If true, the bridge exits if it fails to bridge any channel. Otherwise, it
# will go on bridging the channels it can bridge. The default is false.
forbid_bridge_failure: true

# A puppet matrix user of a real mattermost user with have matrix localpart
# with this prefix.
matrix_localpart_prefix: 'mm_'
# Template for the matrix display name of puppet users. The following
# variables are available:
# - [USERNAME] is the mattermost username
# - [DISPLAY] is the Mattermost display name. This is the concatenation of first
#   and last names if either is set, or the username otherwise.
#
# This is optional and defaults to [DISPLAY]
matrix_display_name_template: '[DISPLAY] [mm]'

# Template for the mattermost usernames of puppet users. The following
# variables are available:
#  - [LOCALPART] is the localpart of the user's id
#  - [DISPLAY] is the matrix display name. If this is not available, the
#    localpart is used.
#
# This is optional and defaults to [DISPLAY]
mattermost_username_template: 'matrix_[LOCALPART]'

# The localpart of the corresponding matrix bot. This is automatically created
# by the bridge.
matrix_bot:
  username: 'matterbot'
  # Optional
  display_name: 'Mattermost Bridge'

# The mattermost bot used by the bridge. This has to be an existing user with
# system administration privileges, in order to verify the emails of the puppet
# users.
#
# Use the username matrix.bridge. The user must have a system admin role
#
mattermost_bot_userid: 'geds3gxhdf81dccdrm8bfx37ry'
mattermost_bot_access_token: 'bxfcapjqiina9xayxw6y65ubwh'
# If password is defined it will be used. 
# Password is a bas64 encoded string of the users password.
matrix_admin:
  username: '@admin:localhost'
  access_token: 'syt_YWRtaW4_ESjBoGLaWtscFgZHsBhJ_027WFj'
  # password: 'QWRtaW4uLjEyMzQ1Ng=='

# Database configuration. Currently only postgres and mysql are supported.
# The configuration is the arguments supplied to TypeORM's datasource:
# https://typeorm.biunav.com/en/data-source.html#what-is-datasource
database:
  type: postgres
  host: localhost
  database: mm-matrix-bridge
  username: mm-matrix-bridge
  password: hunter2
  # port: 5432

logging: debug # Valid values are trace, debug, info, warn, error and silent

# Matrix users that should not show up on the other side of the bridge. The bot
# user (matterbot) is automatically included.
ignored_matrix_users:
  - '@admin:localhost'
  - '@ignored_user:localhost'

# Same as above. The mattermost bot is also automatically included.
ignored_mattermost_users:
  - 'whida44gqpyfierua1wfrnbxtr'

# Email template used for puppet users, with [RANDOM] replaced by a random
# string. These do not have to be valid emails, as the users have their emails
# automatically verified. However, this can pose a security issue if third
# parties can potentially control these email addresses.
#
mattermost_email_template: 'devnull-[RANDOM]@localhost'
