version: '3.0'
services:
  postgres:
    restart: unless-stopped
    image: postgres:15.1-alpine
    volumes:
      - ./backup/mattermost.sql:/docker-entrypoint-initdb.d/00-mattermost.sql
      - ./postgres/setup-synapse.sql:/docker-entrypoint-initdb.d/01-setup-synapse.sql
      - ./backup/synapse.sql:/docker-entrypoint-initdb.d/02-synapse.sql
      - ./postgres/setup-bridge.sql:/docker-entrypoint-initdb.d/03-setup-bridge.sql
      - ./backup/mm-matrix-bridge.sql:/docker-entrypoint-initdb.d/04-mm-matrix-bridge.sql
      - ./docker-scripts/dump_db.sh:/dump_db.sh

    environment:
      #We create synapse database in 01-setup.sql
      - POSTGRES_USER=mattermost
      - POSTGRES_DB=mattermost
      - POSTGRES_PASSWORD=hunter2
    ports:
      - '5432:5432'
    networks:
      - my_net

  matrix:
    build: matrix
    # image: matrixdotorg/synapse:latest
    restart: unless-stopped
    networks:
      - my_net
    ports:
      - '8008:8008'
    volumes:
      - ./matrix/data:/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    depends_on:
      - postgres
  synapse-admin:
    container_name: synapse-admin
    hostname: synapse-admin
    build:
      context: https://github.com/Awesome-Technologies/synapse-admin.git
      # args:
      #   - NODE_OPTIONS="--max_old_space_size=1024"
      #   # see #266, PUBLIC_URL must be without surrounding quotation marks
      #   - PUBLIC_URL=/synapse-admin
      #   - REACT_APP_SERVER="https://matrix.example.com"
    ports:
      - "8081:80"
    networks:
      - my_net
    restart: unless-stopped

  mattermost:
    build: mattermost
    restart: unless-stopped
    ports:
      - '8065:8065'
      - '80:8065'
    networks:
      - my_net
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    depends_on:
      - postgres

  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./element/element-config.json:/app/config.json
    ports:
      - '8080:80'
    networks:
      - my_net
    depends_on:
      - matrix
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
